# Generated by Django 5.2 on 2025-06-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('sender', models.CharField(default='', max_length=100)),
                ('receiver', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
