# Generated by Django 5.2 on 2025-07-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('projects', models.CharField(default='', max_length=100)),
                ('education', models.CharField(default='', max_length=100)),
                ('skill_pack', models.CharField(default='', max_length=100)),
                ('image', models.URLField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('c_title', models.CharField(default='', max_length=100)),
                ('linkedin', models.CharField(default='', max_length=100)),
                ('github', models.CharField(default='', max_length=100)),
                ('whatsapp', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('logo_title', models.CharField(default='', max_length=100)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('skill_title', models.CharField(default='', max_length=100)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(blank=True, max_length=700, null=True)),
                ('cv', models.URLField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LatestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_one', models.CharField(default='', max_length=100)),
                ('s_two', models.CharField(default='', max_length=100)),
                ('p_name', models.CharField(default='', max_length=100)),
                ('p_skills', models.CharField(default='', max_length=100)),
                ('p_url', models.CharField(default='', max_length=300)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=100)),
                ('p_skills', models.CharField(default='', max_length=100)),
                ('p_url', models.CharField(default='', max_length=300)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/images/')),
            ],
        ),
    ]
