# Generated by Django 5.2 on 2025-07-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestinfo',
            name='username',
        ),
        migrations.AlterField(
            model_name='latestinfo',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/images/'),
        ),
    ]
