# Generated by Django 5.2 on 2025-06-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeinfo',
            old_name='receiver',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='homeinfo',
            old_name='sender',
            new_name='logo_title',
        ),
        migrations.RemoveField(
            model_name='homeinfo',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='homeinfo',
            name='sr',
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='cv',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/cv/'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/images/'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='skill_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
