# Generated by Django 5.2 on 2025-07-06 04:58


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestinfo',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
