# Generated by Django 5.2 on 2025-06-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_receiver_homeinfo_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.CharField(default='', max_length=100)),
                ('education', models.CharField(default='', max_length=100)),
                ('skill_pack', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/images/')),
            ],
        ),
    ]
