# Generated by Django 5.2 on 2025-07-05 16:00

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_latestinfo_username_alter_latestinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestinfo',
            name='username',
            field=models.CharField(max_length=100, default=''),
        ),
    ]
