# Generated by Django 5.2 on 2025-07-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_add_username_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestinfo',
            name='username',
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
