# Generated by Django 5.2 on 2025-07-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_latestinfo_username_footerinfo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestinfo',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projectsinfo',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='latestinfo',
            name='image',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='projectsinfo',
            name='image',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
    ]
