# Generated by Django 5.2 on 2025-06-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_footerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=100)),
                ('p_skills', models.CharField(default='', max_length=100)),
                ('p_url', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/images/')),
            ],
        ),
    ]
