# Generated by Django 5.2 on 2025-07-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_latestinfo_username_projectsinfo_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestinfo',
            name='s_one',
        ),
        migrations.RemoveField(
            model_name='latestinfo',
            name='s_two',
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='s_one',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='s_two',
            field=models.CharField(default='', max_length=100),
        ),
    ]
