# Generated by Django 5.2 on 2025-07-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_latestinfo_s_one_remove_latestinfo_s_two_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestInfo',
        ),
    ]
