# Generated by Django 5.2 on 2025-06-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_latestinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestinfo',
            name='p_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='projectsinfo',
            name='p_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
