# Generated by Django 4.2.13 on 2026-05-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('device', models.CharField(blank=True, default='', max_length=50)),
                ('browser', models.CharField(blank=True, default='', max_length=50)),
                ('section', models.CharField(blank=True, default='home', max_length=50)),
            ],
        ),
    ]
