# Generated by Django 5.2 on 2025-06-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_registeruser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterUser',
            new_name='RegUser',
        ),
    ]
