# Generated by Django 4.2.13 on 2026-06-04 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0009_portfoliolink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliolink',
            name='label',
        ),
        migrations.RemoveField(
            model_name='portfoliolink',
            name='utm_params',
        ),
        migrations.AlterField(
            model_name='portfoliolink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_link', to=settings.AUTH_USER_MODEL),
        ),
    ]
