# Generated by Django 5.2 on 2025-07-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_rename_registeruser_reguser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegUser',
        ),
    ]
