# Generated by Django 5.2 on 2025-07-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_delete_reguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
