# Generated by Django 4.2.13 on 2026-06-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_portfoliolink_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='skill_pack',
            field=models.CharField(default='', max_length=300),
        ),
    ]
