# Generated by Django 5.2 on 2025-07-03 14:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_homeinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cv'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
