# Generated by Django 4.2.13 on 2026-06-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_aboutinfo_skill_pack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliolink',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='portfoliolink',
            name='created_at',
        ),
    ]
