# Generated by Django 5.2 on 2025-07-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_homeinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='cv',
            field=models.FileField(blank=True, default=None, null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='portfolio/'),
        ),
    ]
