# Generated by Django 4.2.13 on 2026-06-05 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_portfoliolink_clicks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('future', models.JSONField(blank=True, default=list)),
                ('developer', models.TextField(blank=True, default='')),
                ('extra_images', models.JSONField(blank=True, default=list)),
                ('github_url', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='portfolio.projectsinfo')),
            ],
        ),
    ]
