# Generated by Django 5.2 on 2025-07-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_homeinfo_cv_alter_homeinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='cv',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='image',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
    ]
