# Generated by Django 4.2.13 on 2026-06-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_projectdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(default='', max_length=200)),
                ('issuer', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.CharField(blank=True, default='', max_length=50)),
                ('verify_url', models.URLField(blank=True, default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('degree', models.CharField(default='', max_length=200)),
                ('cgpa', models.CharField(blank=True, default='', max_length=20)),
                ('university', models.CharField(default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('session', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(default='', max_length=200)),
                ('company', models.CharField(default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('dates', models.CharField(blank=True, default='', max_length=100)),
                ('bullets', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HobbyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('hobby', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSpoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('language', models.CharField(default='', max_length=100)),
                ('proficiency', models.CharField(choices=[('Native', 'Native'), ('Fluent', 'Fluent'), ('Professional', 'Professional'), ('Intermediate', 'Intermediate'), ('Basic', 'Basic')], default='Professional', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('linkedin', models.URLField(blank=True, default='', max_length=300)),
                ('github', models.URLField(blank=True, default='', max_length=300)),
                ('portfolio_url', models.CharField(blank=True, default='', max_length=300)),
                ('twitter', models.URLField(blank=True, default='', max_length=300)),
                ('website', models.URLField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('summary', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkillInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('skill', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
