# Generated by Django 5.2 on 2025-07-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_homeinfo_cv_alter_homeinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='image',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
    ]
