# Generated by Django 5.2 on 2025-07-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_aboutinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
