# Generated by Django 4.2.13 on 2026-06-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_achievementinfo_certificationinfo_educationinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='cv_mode',
            field=models.CharField(choices=[('generated', 'Generated'), ('uploaded', 'Uploaded')], default='generated', max_length=20),
        ),
    ]
