# Generated by Django 4.2.13 on 2026-06-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_homeinfo_cv_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='cv_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word')], default='pdf', max_length=10),
        ),
    ]
