# Generated by Django 5.2 on 2025-07-05 05:05

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_aboutinfo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestinfo',
            name='username',
            field=models.URLField(max_length=700, blank=True, null=True),

        ),
    ]
