# Generated by Django 4.2.13 on 2026-06-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_homeinfo_cv_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('file_name', models.CharField(blank=True, default='', max_length=100)),
                ('font_family', models.CharField(default='Times New Roman', max_length=50)),
                ('font_size', models.PositiveSmallIntegerField(default=12)),
                ('line_spacing', models.FloatField(default=1.2)),
                ('heading_color', models.CharField(default='#000000', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('accent_color', models.CharField(default='#000000', max_length=7)),
                ('page_size', models.CharField(default='A4', max_length=10)),
                ('margin_top', models.FloatField(default=12)),
                ('margin_bottom', models.FloatField(default=12)),
                ('margin_left', models.FloatField(default=13)),
                ('margin_right', models.FloatField(default=13)),
                ('section_padding', models.FloatField(default=8)),
                ('sections_order', models.JSONField(default=list)),
                ('sections_visible', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
