# Generated by Django 4.2.13 on 2026-06-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_cvpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationinfo',
            name='image',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
    ]
